<<<<<<< HEAD
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  version: "3.11"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: documentation/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
=======
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: documentation/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
>>>>>>> 52942b828f42a7d1f288afe6d867802f0ec85c3c
