version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  version: "3.11"
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: documentation/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
